# Stage 1 — dev server
FROM alpine:latest AS build

# Install Hugo Extended and Go
RUN apk add --update --no-cache hugo go git

RUN hugo version && go version

WORKDIR /src

COPY . .

# Download Hugo modules
RUN hugo mod get

EXPOSE 1313

CMD ["hugo", "server", "--bind", "0.0.0.0", "--port", "1313", "--buildDrafts", "--buildFuture", "--environment", "development"]
